-- LLM Auditor — skema Postgres (pengganti SQLite + sqlite-vec).
--
-- Dijalankan lewat `npm run db:schema` (lihat scripts/apply_schema.js), BUKAN
-- langsung dengan psql: token {{GAP_THRESHOLD}} di bawah disubstitusi dari
-- konstanta GAP_THRESHOLD di lib/db.js supaya ambang gap hanya punya satu
-- sumber kebenaran.
--
-- Catatan tipe:
--   · Kolom waktu sengaja TEXT berisi ISO-8601, persis seperti versi SQLite —
--     seluruh perbandingan di kode berbentuk string (`expires_at > $1`) dan
--     view memakai substr(taken_at, 1, 7) untuk bucket bulanan.
--   · id memakai GENERATED BY DEFAULT (bukan ALWAYS) agar skrip migrasi bisa
--     menulis id asal dari SQLite; sequence disinkronkan setelahnya.
--   · Agregat di-cast eksplisit ke int/float8 karena driver Postgres
--     mengembalikan bigint & numeric sebagai STRING — tanpa cast, penjumlahan
--     di JS akan berubah jadi penggabungan string.

CREATE EXTENSION IF NOT EXISTS vector;

-- ---------------------------------------------------------------------------
-- Tabel dasar
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS divisions (
  id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS topics (
  id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  area text
);

CREATE TABLE IF NOT EXISTS employees (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          text NOT NULL,
  email         text,
  role          text NOT NULL DEFAULT 'employee',   -- employee | auditor | director | super_admin
  division_id   integer NOT NULL REFERENCES divisions(id),
  password_hash text,
  status        text NOT NULL DEFAULT 'active',
  created_at    text
);
-- Satu akun per alamat email, tanpa memandang besar-kecil huruf
-- (pengganti `email COLLATE NOCASE` milik SQLite).
CREATE UNIQUE INDEX IF NOT EXISTS idx_employees_email ON employees (lower(email));

CREATE TABLE IF NOT EXISTS quiz_attempts (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id integer NOT NULL REFERENCES employees(id),
  topic_id    integer NOT NULL REFERENCES topics(id),
  score       integer NOT NULL,          -- 0..100
  taken_at    text NOT NULL              -- 'YYYY-MM-DD'
);
CREATE INDEX IF NOT EXISTS idx_attempts_employee ON quiz_attempts (employee_id);
CREATE INDEX IF NOT EXISTS idx_attempts_topic    ON quiz_attempts (topic_id);

CREATE TABLE IF NOT EXISTS recommendations (
  id                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope_type         text NOT NULL,      -- employee | division
  scope_ref          integer NOT NULL,
  scope_label        text NOT NULL,
  title              text NOT NULL,
  gap_summary        text,
  recommendation     text,
  recommended_topics text,               -- JSON string
  model              text,
  created_by         text,
  status             text NOT NULL DEFAULT 'pending',  -- pending | acknowledged
  ack_by             text,
  ack_note           text,
  ack_at             text,
  created_at         text NOT NULL
);

CREATE TABLE IF NOT EXISTS quiz_sessions (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id   integer NOT NULL REFERENCES employees(id),
  topic_id      integer NOT NULL REFERENCES topics(id),
  payload       text NOT NULL,           -- JSON: soal + answer_index + explanation
  num_questions integer NOT NULL,
  status        text NOT NULL DEFAULT 'open',   -- open | submitted
  score         integer,
  model         text,
  created_at    text NOT NULL,
  submitted_at  text
);

CREATE TABLE IF NOT EXISTS app_settings (
  key   text PRIMARY KEY,
  value text
);

-- Sesi login: token acak yang disimpan ter-hash.
CREATE TABLE IF NOT EXISTS sessions (
  token_hash  text PRIMARY KEY,
  employee_id integer NOT NULL REFERENCES employees(id),
  created_at  text NOT NULL,
  expires_at  text NOT NULL,
  user_agent  text
);
CREATE INDEX IF NOT EXISTS idx_sessions_employee ON sessions (employee_id);

-- Throttle login. Di versi SQLite ini sebuah Map in-memory; di lingkungan
-- serverless setiap request bisa proses baru, jadi hitungannya harus tinggal
-- di database agar proteksi brute-force benar-benar berlaku.
CREATE TABLE IF NOT EXISTS login_attempts (
  email    text PRIMARY KEY,
  count    integer NOT NULL DEFAULT 0,
  first_at text NOT NULL
);

-- ---------------------------------------------------------------------------
-- RAG: dokumen PDF + chunk ber-embedding (pengganti vec0)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pdf_documents (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  filename   text NOT NULL,
  title      text,
  num_pages  integer,
  num_chunks integer NOT NULL DEFAULT 0,
  bytes      integer,
  chars      integer,
  created_at text NOT NULL
);

CREATE TABLE IF NOT EXISTS pdf_chunks (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doc_id      integer NOT NULL REFERENCES pdf_documents(id) ON DELETE CASCADE,
  chunk_index integer NOT NULL,
  content     text NOT NULL,
  embedding   vector(3072)               -- gemini-embedding-001, sudah L2-normalized
);
CREATE INDEX IF NOT EXISTS idx_pdf_chunks_doc ON pdf_chunks (doc_id);
-- Sengaja TANPA index vektor: korpusnya ratusan chunk, sequential scan sudah
-- sub-milidetik. HNSW pada tipe `vector` dibatasi 2000 dimensi, jadi kalau
-- korpus tumbuh besar pindahkan kolom ini ke halfvec(3072) lalu index HNSW.

-- ---------------------------------------------------------------------------
-- View analitik — semantik "gap" (skor < ambang) ditanam di lapisan data
-- supaya SQL Agent bisa menjawab pertanyaan gap secara konsisten.
-- ---------------------------------------------------------------------------
DROP VIEW IF EXISTS v_employee_score;
DROP VIEW IF EXISTS v_topic_score;
DROP VIEW IF EXISTS v_division_score;
DROP VIEW IF EXISTS v_division_topic;
DROP VIEW IF EXISTS v_employee_topic;

-- Skor seorang karyawan pada satu topik = nilai TERBAIK (MAX) attempt-nya,
-- konsisten dengan tampilan peserta & logika retake.
CREATE VIEW v_employee_topic AS
  SELECT e.id AS employee_id, e.name AS employee, d.name AS division,
         t.id AS topic_id, t.name AS topic,
         MAX(qa.score) AS avg_score,
         CASE WHEN MAX(qa.score) < {{GAP_THRESHOLD}} THEN 1 ELSE 0 END AS is_gap,
         COUNT(*)::int AS attempts
  FROM quiz_attempts qa
  JOIN employees e ON e.id = qa.employee_id
  JOIN divisions d ON d.id = e.division_id
  JOIN topics    t ON t.id = qa.topic_id
  WHERE e.role = 'employee'
  GROUP BY e.id, e.name, d.name, t.id, t.name;

-- Agregat berikut diturunkan dari v_employee_topic sehingga "avg_score" berarti
-- rata-rata dari nilai TERBAIK tiap karyawan, bukan rata-rata semua attempt.
CREATE VIEW v_division_topic AS
  SELECT d.id AS division_id, et.division, et.topic_id, et.topic,
         ROUND(AVG(et.avg_score), 1)::float8 AS avg_score,
         CASE WHEN AVG(et.avg_score) < {{GAP_THRESHOLD}} THEN 1 ELSE 0 END AS is_gap,
         COUNT(*)::int AS employees,
         SUM(et.attempts)::int AS attempts
  FROM v_employee_topic et
  JOIN divisions d ON d.name = et.division
  GROUP BY d.id, et.division, et.topic_id, et.topic;

CREATE VIEW v_division_score AS
  SELECT d.id AS division_id, et.division,
         ROUND(AVG(et.avg_score), 1)::float8 AS avg_score,
         SUM(et.attempts)::int AS attempts
  FROM v_employee_topic et
  JOIN divisions d ON d.name = et.division
  GROUP BY d.id, et.division;

CREATE VIEW v_topic_score AS
  SELECT et.topic_id, et.topic, t.area,
         ROUND(AVG(et.avg_score), 1)::float8 AS avg_score,
         SUM(et.attempts)::int AS attempts,
         CASE WHEN AVG(et.avg_score) < {{GAP_THRESHOLD}} THEN 1 ELSE 0 END AS is_gap
  FROM v_employee_topic et
  JOIN topics t ON t.id = et.topic_id
  GROUP BY et.topic_id, et.topic, t.area;

CREATE VIEW v_employee_score AS
  SELECT et.employee_id, et.employee, et.division,
         ROUND(AVG(et.avg_score), 1)::float8 AS avg_score,
         SUM(et.attempts)::int AS attempts,
         SUM(et.is_gap)::int AS gap_topics
  FROM v_employee_topic et
  GROUP BY et.employee_id, et.employee, et.division;
